[package]
name = "price-aggregator-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.price-aggregator]
path = ".."

[dependencies.dharitri-wasm]
version = "0.10.2"

[dependencies.dharitri-wasm-debug]
version = "0.10.2"
