[package]
name = "oracle-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.oracle]
path = ".."

[dependencies.dharitri-wasm]
version = "0.9.8"

[dependencies.dharitri-wasm-debug]
version = "0.9.8"
