[package]
name = "module-test-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.module-test]
path = ".."

[dependencies.dharitri-wasm]
version = "0.9.8"

[dependencies.dharitri-wasm-debug]
version = "0.9.8"
