[package]
name = "price-aggregator-proxy"
version = "0.0.0"
authors = [ "",]
edition = "2018"

[dependencies.dharitri-wasm]
version = "0.9.8"

[dependencies.dharitri-wasm-derive]
version = "0.9.8"

[dev-dependencies.dharitri-wasm-debug]
version = "0.9.8"
