[Blockchain]
    GasPrice = 1_000_000_000
    ProxyUrl = "https://devnet-gateway.dharitri.com"
    ChainID = "D"
    PemPath = "./config/owner.pem"

[GasConfig]
    BatchTxGasLimit = 215_000_000
    FeedTxGasLimit = 30_000_000

[Server]
    Port = ":5000"

[Contract]
    Endpoint = "submit"
    Address = "moa1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sy862lj"

[PriceFeedBatch]
    Endpoint = "submitBatch"
    Addresses = [
        "moa1qqqqqqqqqqqqqpgqdegftahwl7vv2a9azusjl9cmx995nzv9707qntclqg",
        "moa1qqqqqqqqqqqqqpgqs8gtvhtt6k7h6khkmudzd6y4z0r08rx4u00spt4fh6",
        "moa1qqqqqqqqqqqqqpgq9k5uafq4ya9ptq9y8795nmh9wysex7jwcvpqm0wuqw"
    ]
    BatchSize = 10

[GasStation]
    Endpoint = "submitBatch"
    Addresses = [
        "moa1qqqqqqqqqqqqqpgqdegftahwl7vv2a9azusjl9cmx995nzv9707qntclqg",
        "moa1qqqqqqqqqqqqqpgqs8gtvhtt6k7h6khkmudzd6y4z0r08rx4u00spt4fh6",
        "moa1qqqqqqqqqqqqqpgq9k5uafq4ya9ptq9y8795nmh9wysex7jwcvpqm0wuqw"
    ]
    TargetAssets = [
        { Ticker = "MOAX", Decimals = 18 },
        { Ticker = "ETH", Decimals = 18 },
        { Ticker = "USDC", Decimals = 6 },
    ]

[Exchange]
    MultiplicationPrecision = 100
    CheckPercentageChange = false
    PercentageThreshold = 2.5
    Pairs = [
        { Base = "MOAX", Quote = "USD" },
        { Base = "ETH", Quote = "USD" },
        { Base = "USDC", Quote = "USD" },
        { Base = "BTC", Quote = "USD" },
        { Base = "AAVE", Quote = "USD" },
        { Base = "LINK", Quote = "USD" },
        { Base = "SOL", Quote = "USD" },
        { Base = "SNX", Quote = "USD" },
        { Base = "YFI", Quote = "USD" },
        { Base = "UNI", Quote = "USD" },
]


